### ISSUE TITLE
Declare list of files in nuspec programatically

### ISSUE THREAD

**Issue by dustinstanley** [Ullink/gradle-nuget-plugin#7]
Is this behavior supported?  I'd like to automatically declare all files in a specific directory without having to list each specific one, e.g.

        delegate.files {
            fileTree(msbuild.destinationDir).each { File entry ->
                delegate.file(src: entry, target: 'lib')
            }
        }

When I do this, I get the error below.  Using delegate.file on the same files outside the above closure works fine, however.

Caused by: org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert the provided notation to a File or URI: {src=build\msbuild\bin\log4net.dll, target=lib}.
The following types/formats are supported:
  - A String or CharSequence path, e.g 'src/main/java' or '/usr/include'
  - A String or CharSequence URI, e.g 'file:/usr/include'
  - A File instance.
  - A URI or URL instance.
        at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:55)
        at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:184)
        at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:69)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:77)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:60)
        at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
        at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:637)
        at org.gradle.groovy.scripts.DefaultScript.file(DefaultScript.java:110)

**Comment by gluck** [comment]
_delegate_ is an implicit variable scope to the current closure.

Writing:

    nuspec { delegate.foo() }

is the same as 

    nuspec { foo() }

but being explicit about the fact that you want to use the method resolving on the XMLBuilder (that is the XML building DSL).

This is needed as gradle scripts already define some methods (file/files) that'll be called otherwise as they're part of any script scope.

In your case as you got out of the XMLBuilder closure (you're in the _each_) closure, the XMLBuilder delegate is no longer available and your stack show that you use Script.file instead of XMLBuilder.file.

Try this instead:

    delegate.files {
        def filesXmlNode = delegate;
        fileTree(msbuild.destinationDir).each { File entry ->
            filesXmlNode.file(src: entry, target: 'lib')
        }
    }

Should work I think.

**Comment by dustinstanley** [comment]
Thanks for the explanation!  That worked nicely.  I will close this issue.
